#!/usr/bin/python3
from argparse import ArgumentParser


if __name__ == '__main__':
    parser = ArgumentParser(description='Evaluator')
    parser.add_argument('predictions',
                        type=str,
                        help='predictions of the model')

    parser.add_argument('truth',
                        type=str,
                        help='ground truth labels')

    args = parser.parse_args()

    with open(args.predictions, 'r') as pf, open(args.truth, 'r') as tf:
        pred = pf.readlines()
        truth = tf.readlines()

        assert len(pred) == len(truth), 'predictions have different sizes'

        hits = sum(p == t for p, t in zip(pred, truth))

        print(f'Model accuracy: {hits / len(truth):2.4f}')
