#!/bin/bash

unzip data.zip || exit 1

echo "#################"
echo "    COMPILING    "
echo "#################"

make || exit 2

echo "#################"
echo "     RUNNING     "
echo "#################"

./network || exit 3


echo "#################"
echo "   EVALUATING    "
echo "#################"

./evaluate testPredictions.csv data/fashion_mnist_test_labels.csv
